; ============================================================
;  Abyss — RC Car
;  Board: Seeed Studio XIAO ESP32C3
; ============================================================
[env:xiaoesp32c3]
platform = espressif32@^6.0.0
board     = seeed_xiao_esp32c3
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    madhephaestus/ESP32Servo   @ ^0.13.0