[env:seeed_xiao_esp32c3]
platform  = espressif32
board     = seeed_xiao_esp32c3
framework = arduino

build_src_filter =
    +<*>

lib_deps =
    olikraus/U8g2 @ ^2.35.19
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.15

monitor_speed = 115200
